### PR TITLE
Added logs to Studio library

### PR DESCRIPTION
**Pull request by ogranada**
Logs added to Studio system.

Logs can be enabled via environment variable:
```bash
DEBUG=Studio node my-studio-app.js
```
or
```bash
export DEBUG=Studio
node my-studio-app.js
```

### CODE REVIEW

**Comment by ogranada** [comment]
Hi Erich, I want to include the log functionality in `Studio-Cluster`, do you think that we should create a common repo or replicate `logging.js` file in both projects?

**Comment by ericholiveira** [comment]
I think we should replicate, to keep studio-cluster completely separate from studio.
I have plans to create a "more complete" microservices framework on the next months using studio, so its best to keep them separate

**Comment by ericholiveira** [comment]
Also let me know if you want to get involved in this new project... i will announce it on slack anyway

**Comment by ogranada-xk** [comment]
Sure, I want to participate.

**Comment by ericholiveira** [comment]
Great... i will let you know... probably starting it in the next month

**Comment by ogranada-xk** [comment]
OK

**Pull request merged**
